### PR TITLE
fix: common mistranscriptions for kde connect

### LINKED ISSUE #5: [BUG] Neon almost never recognizes "pair kde connect"
### Description

Basically what the title says - Neon just can't seem to recognize this. Enunciating each letter and pausing for 0.5-1 second in between seems to help, but _definitely_ doesn't work all the time. `pair katie econnect` seems to be a particularly common transcription, anecdotally.

Matrix thread: https://matrix.to/#/!XeBSsfCqDoWgGMihCz:matrix.org/$KXpLndM-L8zTUkmXGwuvhefFphaTPC33E3d9RTpffNI?via=matrix.org&via=strugee.net&via=matrix.freyachat.eu

### Steps to Reproduce

_No response_

### Relevant Code

_No response_

### Other Notes

`voice.log` from when I was initially trying to get this to work (I thought an update was _already_ running, but the logs seem to indicate maybe not...): 
[2023-07-10_14-44-voice.log](https://github.com/NeonGeckoCom/skill-mark2-audio-receiver/files/12494099/2023-07-10_14-44-voice.log)

I _think_ the corresponding `skills.log` (not sure cause the utterances don't seem to completely match up and the timestamps don't either, but it's from the same log directory as the above `voice.log` and grepping for the utterances I expected turns up nothing, even in the file I pulled that `voice.log` from a couple hours ago...): 
[skills.log](https://github.com/NeonGeckoCom/skill-mark2-audio-receiver/files/12494109/skills.log)

Honestly, these logs are so weird I can try and capture some cleaner ones later if it would be helpful. Also I can record the way I speak this phrase.

### PR DESCRIPTION
**Pull request by mikejgray**
# Description
Add some commonly mistranscribed utterances from Neon's default STT.

# Issues
Closes #5

### CODE REVIEW

**Comment by mikejgray** [comment]
@strugee if you'd like to try these changes, add `git+https://github.com/NeonGeckoCom/skill-mark2-audio-receiver@FIX_kde-connect-intents` to your `skills.default_skills` section of neon.yaml. If that section doesn't exist, you'll need to add it. Would love your feedback on this one before pushing it out.

**Review by NeonDaniel — APPROVED** [review]

**Comment by strugee** [comment]
I'm poking at some other bugs as I mentioned on Matrix, but this seems a lot better - it definitely still requires some level of active enunciation though. For the record, here's some more transcriptions I pulled from `grep transcribed logs/voice.log`:

```
2023-09-06 20:40:39.064 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: turkey connect
2023-09-06 20:41:06.364 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: are Katie econnect
2023-09-06 20:41:18.621 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: enable can you connect
2023-09-06 20:41:39.969 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: enable Katie econnect
2023-09-06 20:42:12.429 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: parakeet connect
2023-09-06 20:42:24.602 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:642 - INFO - nothing transcribed
2023-09-06 20:42:34.462 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: are Katie econnect
2023-09-06 20:43:32.812 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: are Katy e connect
2023-09-06 20:44:01.933 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: are Katie econnect
2023-09-06 20:47:12.507 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: enable cancel
2023-09-06 20:47:24.972 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: are Katie econnect
2023-09-06 20:49:00.609 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: pair kdee connect
```

Not sure exactly how wide you want to make the intent here.

**Comment by mikejgray** [comment]
> I'm poking at some other bugs as I mentioned on Matrix, but this seems a lot better - it definitely still requires some level of active enunciation though. For the record, here's some more transcriptions I pulled from `grep transcribed logs/voice.log`:
> 
> ```
> 2023-09-06 20:40:39.064 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: turkey connect
> 2023-09-06 20:41:06.364 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: are Katie econnect
> 2023-09-06 20:41:18.621 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: enable can you connect
> 2023-09-06 20:41:39.969 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: enable Katie econnect
> 2023-09-06 20:42:12.429 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: parakeet connect
> 2023-09-06 20:42:24.602 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:642 - INFO - nothing transcribed
> 2023-09-06 20:42:34.462 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: are Katie econnect
> 2023-09-06 20:43:32.812 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: are Katy e connect
> 2023-09-06 20:44:01.933 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: are Katie econnect
> 2023-09-06 20:47:12.507 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: enable cancel
> 2023-09-06 20:47:24.972 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: are Katie econnect
> 2023-09-06 20:49:00.609 - voice - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:640 - INFO - transcribed: pair kdee connect
> ```
> 
> Not sure exactly how wide you want to make the intent here.

Thanks for the feedback! I don't want to make it too much wider, but it sounds like we're narrowing it down pretty well. I think one more pass should do it.

I've also asked Daniel to see if we can add KDE Connect to the vocabulary list for the Google STT plugin, which should head off the issue at the source. Not sure if he has cycles/intentions of doing so but it never hurts to ask!

**Comment by strugee** [comment]
> I've also asked Daniel to see if we can add KDE Connect to the vocabulary list for the Google STT plugin

Oh, I didn't even realize this was an option - I just assumed the Google backend was a black box. That would be way better.

**Pull request merged**
